# Generated by Django 3.2.5 on 2022-03-04 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blognew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='blognew/')),
                ('date123', models.DateField(default=datetime.datetime.now)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
