# Generated by Django 3.2.5 on 2022-03-04 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blognew',
            name='date123',
        ),
    ]
