# Generated by Django 3.2.5 on 2022-03-08 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_blognew_date123'),
    ]

    operations = [
        migrations.AddField(
            model_name='blognew',
            name='date123',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
