# Generated by Django 3.2.5 on 2022-03-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_blognew_date123'),
    ]

    operations = [
        migrations.AddField(
            model_name='blognew',
            name='join',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blognew',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blognew',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='blognew',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blognew/'),
        ),
        migrations.AlterField(
            model_name='blognew',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
