# Generated by Django 3.2.5 on 2022-03-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20220308_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blognew',
            old_name='join',
            new_name='link',
        ),
    ]
