# Generated by Django 3.2.5 on 2022-03-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_contactlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=800)),
            ],
        ),
        migrations.DeleteModel(
            name='contactlist',
        ),
    ]
