# Generated by Django 3.2.5 on 2022-03-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20220309_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio_photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio_photos/')),
            ],
        ),
    ]
