# Generated by Django 3.2.5 on 2022-03-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_portfolio_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blognew',
            name='link',
        ),
        migrations.AlterField(
            model_name='blognew',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
