# Generated by Django 3.2.5 on 2022-03-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
